---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8081
      imagePullSecrets:
        - name: backend-docker-config-secret